User.create(name: Faker::Name.name, email: 'author01@example.com', password: 'password')
User.create(name: Faker::Name.name, email: 'author02@example.com', password: 'password')
User.create(name: Faker::Name.name, email: 'reviewer01@example.com', password: 'password')
User.create(name: Faker::Name.name, email: 'reviewer02@example.com', password: 'password')
User.create(name: Faker::Name.name, email: 'admin@example.com', password: 'password')
