default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres

production:
  <<: *default
  database: eclipro

development:
  <<: *default
  database: eclipro_development

test:
  <<: *default
  database: eclipro_test
